version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: content_filter_db
    ports:
      - '5433:5432'  # Changed from '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: